server {
    listen 80;
    server_name localhost;

    # Compresión Gzip para optimizar la carga de los bundles de Flutter Web
    gzip on;
    gzip_minimum_length 1000;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Soporte para ruteo SPA (GoRouter con Path URL Strategy)
        try_files $uri $uri/ /index.html;
    }

    # Caché estricto para assets estáticos que tienen hashes en el nombre
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|mp4)$ {
        root /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
