// Copyright 2026 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file or at https://developers.google.com/open-source/licenses/bsd.

class Country {
  final String name;
  final String code;
  final String flag;
  final String dialCode;

  const Country({
    required this.name,
    required this.code,
    required this.flag,
    required this.dialCode,
  });

  String get displayName => '$name $flag ($dialCode)';
}

const List<Country> countriesList = [
  Country(name: 'Afganistán', code: 'AF', flag: '🇦🇫', dialCode: '+93'),
  Country(name: 'Albania', code: 'AL', flag: '🇦🇱', dialCode: '+355'),
  Country(name: 'Alemania', code: 'DE', flag: '🇩🇪', dialCode: '+49'),
  Country(name: 'Andorra', code: 'AD', flag: '🇦🇩', dialCode: '+376'),
  Country(name: 'Angola', code: 'AO', flag: '🇦🇴', dialCode: '+244'),
  Country(name: 'Antigua y Barbuda', code: 'AG', flag: '🇦🇬', dialCode: '+1'),
  Country(name: 'Arabia Saudita', code: 'SA', flag: '🇸🇦', dialCode: '+966'),
  Country(name: 'Argelia', code: 'DZ', flag: '🇩🇿', dialCode: '+213'),
  Country(name: 'Argentina', code: 'AR', flag: '🇦🇷', dialCode: '+54'),
  Country(name: 'Armenia', code: 'AM', flag: '🇦🇲', dialCode: '+374'),
  Country(name: 'Australia', code: 'AU', flag: '🇦🇺', dialCode: '+61'),
  Country(name: 'Austria', code: 'AT', flag: '🇦🇹', dialCode: '+43'),
  Country(name: 'Azerbaiyán', code: 'AZ', flag: '🇦🇿', dialCode: '+994'),
  Country(name: 'Bahamas', code: 'BS', flag: '🇧🇸', dialCode: '+1'),
  Country(name: 'Bangladés', code: 'BD', flag: '🇧🇩', dialCode: '+880'),
  Country(name: 'Barbados', code: 'BB', flag: '🇧🇧', dialCode: '+1'),
  Country(name: 'Baréin', code: 'BH', flag: '🇧🇭', dialCode: '+973'),
  Country(name: 'Bélgica', code: 'BE', flag: '🇧🇪', dialCode: '+32'),
  Country(name: 'Belice', code: 'BZ', flag: '🇧🇿', dialCode: '+501'),
  Country(name: 'Benín', code: 'BJ', flag: '🇧🇯', dialCode: '+229'),
  Country(name: 'Bielorrusia', code: 'BY', flag: '🇧🇾', dialCode: '+375'),
  Country(name: 'Bolivia', code: 'BO', flag: '🇧🇴', dialCode: '+591'),
  Country(
    name: 'Bosnia y Herzegovina',
    code: 'BA',
    flag: '🇧🇦',
    dialCode: '+387',
  ),
  Country(name: 'Botsuana', code: 'BW', flag: '🇧🇼', dialCode: '+267'),
  Country(name: 'Brasil', code: 'BR', flag: '🇧🇷', dialCode: '+55'),
  Country(name: 'Brunéi', code: 'BN', flag: '🇧🇳', dialCode: '+673'),
  Country(name: 'Bulgaria', code: 'BG', flag: '🇧🇬', dialCode: '+359'),
  Country(name: 'Burkina Faso', code: 'BF', flag: '🇧🇫', dialCode: '+226'),
  Country(name: 'Burundi', code: 'BI', flag: '🇧🇮', dialCode: '+257'),
  Country(name: 'Bután', code: 'BT', flag: '🇧🇹', dialCode: '+975'),
  Country(name: 'Cabo Verde', code: 'CV', flag: '🇨🇻', dialCode: '+238'),
  Country(name: 'Camboya', code: 'KH', flag: '🇰🇭', dialCode: '+855'),
  Country(name: 'Camerún', code: 'CM', flag: '🇨🇲', dialCode: '+237'),
  Country(name: 'Canadá', code: 'CA', flag: '🇨🇦', dialCode: '+1'),
  Country(name: 'Catar', code: 'QA', flag: '🇶🇦', dialCode: '+974'),
  Country(name: 'Chad', code: 'TD', flag: '🇹🇩', dialCode: '+235'),
  Country(name: 'Chile', code: 'CL', flag: '🇨🇱', dialCode: '+56'),
  Country(name: 'China', code: 'CN', flag: '🇨🇳', dialCode: '+86'),
  Country(name: 'Chipre', code: 'CY', flag: '🇨🇾', dialCode: '+357'),
  Country(name: 'Colombia', code: 'CO', flag: '🇨🇴', dialCode: '+57'),
  Country(name: 'Comoras', code: 'KM', flag: '🇰🇲', dialCode: '+269'),
  Country(name: 'Corea del Norte', code: 'KP', flag: '🇰🇵', dialCode: '+850'),
  Country(name: 'Corea del Sur', code: 'KR', flag: '🇰🇷', dialCode: '+82'),
  Country(name: 'Costa de Marfil', code: 'CI', flag: '🇨🇮', dialCode: '+225'),
  Country(name: 'Costa Rica', code: 'CR', flag: '🇨🇷', dialCode: '+506'),
  Country(name: 'Croacia', code: 'HR', flag: '🇭🇷', dialCode: '+385'),
  Country(name: 'Cuba', code: 'CU', flag: '🇨🇺', dialCode: '+53'),
  Country(name: 'Dinamarca', code: 'DK', flag: '🇩🇰', dialCode: '+45'),
  Country(name: 'Dominica', code: 'DM', flag: '🇩🇲', dialCode: '+1'),
  Country(name: 'Ecuador', code: 'EC', flag: '🇪🇨', dialCode: '+593'),
  Country(name: 'Egipto', code: 'EG', flag: '🇪🇬', dialCode: '+20'),
  Country(name: 'El Salvador', code: 'SV', flag: '🇸🇻', dialCode: '+503'),
  Country(
    name: 'Emiratos Árabes Unidos',
    code: 'AE',
    flag: '🇦🇪',
    dialCode: '+971',
  ),
  Country(name: 'Eritrea', code: 'ER', flag: '🇪🇷', dialCode: '+291'),
  Country(name: 'Eslovaquia', code: 'SK', flag: '🇸🇰', dialCode: '+421'),
  Country(name: 'Eslovenia', code: 'SI', flag: '🇸🇮', dialCode: '+386'),
  Country(name: 'España', code: 'ES', flag: '🇪🇸', dialCode: '+34'),
  Country(name: 'Estados Unidos', code: 'US', flag: '🇺🇸', dialCode: '+1'),
  Country(name: 'Estonia', code: 'EE', flag: '🇪🇪', dialCode: '+372'),
  Country(name: 'Etiopía', code: 'ET', flag: '🇪🇹', dialCode: '+251'),
  Country(name: 'Filipinas', code: 'PH', flag: '🇵🇭', dialCode: '+63'),
  Country(name: 'Finlandia', code: 'FI', flag: '🇫🇮', dialCode: '+358'),
  Country(name: 'Fiyi', code: 'FJ', flag: '🇫🇯', dialCode: '+679'),
  Country(name: 'Francia', code: 'FR', flag: '🇫🇷', dialCode: '+33'),
  Country(name: 'Gabón', code: 'GA', flag: '🇬🇦', dialCode: '+241'),
  Country(name: 'Gambia', code: 'GM', flag: '🇬🇲', dialCode: '+220'),
  Country(name: 'Georgia', code: 'GE', flag: '🇬🇪', dialCode: '+995'),
  Country(name: 'Ghana', code: 'GH', flag: '🇬🇭', dialCode: '+233'),
  Country(name: 'Granada', code: 'GD', flag: '🇬🇩', dialCode: '+1'),
  Country(name: 'Grecia', code: 'GR', flag: '🇬🇷', dialCode: '+30'),
  Country(name: 'Guatemala', code: 'GT', flag: '🇬🇹', dialCode: '+502'),
  Country(name: 'Guyana', code: 'GY', flag: '🇬🇾', dialCode: '+592'),
  Country(name: 'Guinea', code: 'GN', flag: '🇬🇳', dialCode: '+224'),
  Country(name: 'Haití', code: 'HT', flag: '🇭🇹', dialCode: '+509'),
  Country(name: 'Honduras', code: 'HN', flag: '🇭🇳', dialCode: '+504'),
  Country(name: 'Hungría', code: 'HU', flag: '🇭🇺', dialCode: '+36'),
  Country(name: 'India', code: 'IN', flag: '🇮🇳', dialCode: '+91'),
  Country(name: 'Indonesia', code: 'ID', flag: '🇮🇩', dialCode: '+62'),
  Country(name: 'Irak', code: 'IQ', flag: '🇮🇶', dialCode: '+964'),
  Country(name: 'Irán', code: 'IR', flag: '🇮🇷', dialCode: '+98'),
  Country(name: 'Irlanda', code: 'IE', flag: '🇮🇪', dialCode: '+353'),
  Country(name: 'Islandia', code: 'IS', flag: '🇮🇸', dialCode: '+354'),
  Country(name: 'Israel', code: 'IL', flag: '🇮🇱', dialCode: '+972'),
  Country(name: 'Italia', code: 'IT', flag: '🇮🇹', dialCode: '+39'),
  Country(name: 'Jamaica', code: 'JM', flag: '🇯🇲', dialCode: '+1'),
  Country(name: 'Japón', code: 'JP', flag: '🇯🇵', dialCode: '+81'),
  Country(name: 'Jordania', code: 'JO', flag: '🇯🇴', dialCode: '+962'),
  Country(name: 'Kazajistán', code: 'KZ', flag: '🇰🇿', dialCode: '+7'),
  Country(name: 'Kenia', code: 'KE', flag: '🇰🇪', dialCode: '+254'),
  Country(name: 'Kirguistán', code: 'KG', flag: '🇰🇬', dialCode: '+996'),
  Country(name: 'Kiribati', code: 'KI', flag: '🇰🇮', dialCode: '+686'),
  Country(name: 'Kuwait', code: 'KW', flag: '🇰🇼', dialCode: '+965'),
  Country(name: 'Laos', code: 'LA', flag: '🇱🇦', dialCode: '+856'),
  Country(name: 'Lesoto', code: 'LS', flag: '🇱🇸', dialCode: '+266'),
  Country(name: 'Letonia', code: 'LV', flag: '🇱🇻', dialCode: '+371'),
  Country(name: 'Líbano', code: 'LB', flag: '🇱🇧', dialCode: '+961'),
  Country(name: 'Liberia', code: 'LR', flag: '🇱🇷', dialCode: '+231'),
  Country(name: 'Libia', code: 'LY', flag: '🇱🇾', dialCode: '+218'),
  Country(name: 'Liechtenstein', code: 'LI', flag: '🇱🇮', dialCode: '+423'),
  Country(name: 'Lituania', code: 'LT', flag: '🇱🇹', dialCode: '+370'),
  Country(name: 'Luxemburgo', code: 'LU', flag: '🇱🇺', dialCode: '+352'),
  Country(
    name: 'Macedonia del Norte',
    code: 'MK',
    flag: '🇲🇰',
    dialCode: '+389',
  ),
  Country(name: 'Madagascar', code: 'MG', flag: '🇲🇬', dialCode: '+261'),
  Country(name: 'Malasia', code: 'MY', flag: '🇲🇾', dialCode: '+60'),
  Country(name: 'Malaui', code: 'MW', flag: '🇲🇼', dialCode: '+265'),
  Country(name: 'Maldivas', code: 'MV', flag: '🇲🇻', dialCode: '+960'),
  Country(name: 'Malí', code: 'ML', flag: '🇲🇱', dialCode: '+223'),
  Country(name: 'Malta', code: 'MT', flag: '🇲🇹', dialCode: '+356'),
  Country(name: 'Marruecos', code: 'MA', flag: '🇲🇦', dialCode: '+212'),
  Country(name: 'Mauricio', code: 'MU', flag: '🇲🇺', dialCode: '+230'),
  Country(name: 'Mauritania', code: 'MR', flag: '🇲🇷', dialCode: '+222'),
  Country(name: 'México', code: 'MX', flag: '🇲🇽', dialCode: '+52'),
  Country(name: 'Micronesia', code: 'FM', flag: '🇫🇲', dialCode: '+691'),
  Country(name: 'Moldavia', code: 'MD', flag: '🇲🇩', dialCode: '+373'),
  Country(name: 'Mónaco', code: 'MC', flag: '🇲🇨', dialCode: '+377'),
  Country(name: 'Mongolia', code: 'MN', flag: '🇲🇳', dialCode: '+976'),
  Country(name: 'Montenegro', code: 'ME', flag: '🇲🇪', dialCode: '+382'),
  Country(name: 'Mozambique', code: 'MZ', flag: '🇲🇿', dialCode: '+258'),
  Country(name: 'Namibia', code: 'NA', flag: '🇳🇦', dialCode: '+264'),
  Country(name: 'Nauru', code: 'NR', flag: '🇳🇷', dialCode: '+674'),
  Country(name: 'Nepal', code: 'NP', flag: '🇳🇵', dialCode: '+977'),
  Country(name: 'Nicaragua', code: 'NI', flag: '🇳🇮', dialCode: '+505'),
  Country(name: 'Níger', code: 'NE', flag: '🇳🇪', dialCode: '+227'),
  Country(name: 'Nigeria', code: 'NG', flag: '🇳🇬', dialCode: '+234'),
  Country(name: 'Noruega', code: 'NO', flag: '🇳🇴', dialCode: '+47'),
  Country(name: 'Nueva Zelanda', code: 'NZ', flag: '🇳🇿', dialCode: '+64'),
  Country(name: 'Omán', code: 'OM', flag: '🇴🇲', dialCode: '+968'),
  Country(name: 'Países Bajos', code: 'NL', flag: '🇳🇱', dialCode: '+31'),
  Country(name: 'Pakistán', code: 'PK', flag: '🇵🇰', dialCode: '+92'),
  Country(name: 'Palaos', code: 'PW', flag: '🇵🇼', dialCode: '+680'),
  Country(name: 'Panamá', code: 'PA', flag: '🇵🇦', dialCode: '+507'),
  Country(
    name: 'Papúa Nueva Guinea',
    code: 'PG',
    flag: '🇵🇬',
    dialCode: '+675',
  ),
  Country(name: 'Paraguay', code: 'PY', flag: '🇵🇾', dialCode: '+595'),
  Country(name: 'Perú', code: 'PE', flag: '🇵🇪', dialCode: '+51'),
  Country(name: 'Polonia', code: 'PL', flag: '🇵🇱', dialCode: '+48'),
  Country(name: 'Portugal', code: 'PT', flag: '🇵🇹', dialCode: '+351'),
  Country(name: 'Puerto Rico', code: 'PR', flag: '🇵🇷', dialCode: '+1'),
  Country(name: 'Reino Unido', code: 'GB', flag: '🇬🇧', dialCode: '+44'),
  Country(
    name: 'República Centroafricana',
    code: 'CF',
    flag: '🇨🇫',
    dialCode: '+236',
  ),
  Country(name: 'República Checa', code: 'CZ', flag: '🇨🇿', dialCode: '+420'),
  Country(
    name: 'República del Congo',
    code: 'CG',
    flag: '🇨🇬',
    dialCode: '+242',
  ),
  Country(
    name: 'República Democrática del Congo',
    code: 'CD',
    flag: '🇨🇩',
    dialCode: '+243',
  ),
  Country(
    name: 'República Dominicana',
    code: 'DO',
    flag: '🇩🇴',
    dialCode: '+1',
  ),
  Country(name: 'Ruanda', code: 'RW', flag: '🇷🇼', dialCode: '+250'),
  Country(name: 'Rumania', code: 'RO', flag: '🇷🇴', dialCode: '+40'),
  Country(name: 'Rusia', code: 'RU', flag: '🇷🇺', dialCode: '+7'),
  Country(name: 'Samoa', code: 'WS', flag: '🇼🇸', dialCode: '+685'),
  Country(
    name: 'San Cristóbal y Nieves',
    code: 'KN',
    flag: '🇰🇳',
    dialCode: '+1',
  ),
  Country(name: 'San Marino', code: 'SM', flag: '🇸🇲', dialCode: '+378'),
  Country(
    name: 'San Vicente y las Granadinas',
    code: 'VC',
    flag: '🇻🇨',
    dialCode: '+1',
  ),
  Country(name: 'Santa Lucía', code: 'LC', flag: '🇱🇨', dialCode: '+1'),
  Country(
    name: 'Santo Tomé y Príncipe',
    code: 'ST',
    flag: '🇸🇹',
    dialCode: '+239',
  ),
  Country(name: 'Senegal', code: 'SN', flag: '🇸🇳', dialCode: '+221'),
  Country(name: 'Serbia', code: 'RS', flag: '🇷🇸', dialCode: '+381'),
  Country(name: 'Seychelles', code: 'SC', flag: '🇸🇨', dialCode: '+248'),
  Country(name: 'Sierra Leona', code: 'SL', flag: '🇸🇱', dialCode: '+232'),
  Country(name: 'Singapur', code: 'SG', flag: '🇸🇬', dialCode: '+65'),
  Country(name: 'Siria', code: 'SY', flag: '🇸🇾', dialCode: '+963'),
  Country(name: 'Somalia', code: 'SO', flag: '🇸🇴', dialCode: '+252'),
  Country(name: 'Sri Lanka', code: 'LK', flag: '🇱🇰', dialCode: '+94'),
  Country(name: 'Sudáfrica', code: 'ZA', flag: '🇿🇦', dialCode: '+27'),
  Country(name: 'Sudán', code: 'SD', flag: '🇸🇩', dialCode: '+249'),
  Country(name: 'Suecia', code: 'SE', flag: '🇸🇪', dialCode: '+46'),
  Country(name: 'Suiza', code: 'CH', flag: '🇨🇭', dialCode: '+41'),
  Country(name: 'Surinam', code: 'SR', flag: '🇸🇷', dialCode: '+597'),
  Country(name: 'Tailandia', code: 'TH', flag: '🇹🇭', dialCode: '+66'),
  Country(name: 'Taiwán', code: 'TW', flag: '🇹🇼', dialCode: '+886'),
  Country(name: 'Tanzania', code: 'TZ', flag: '🇹🇿', dialCode: '+255'),
  Country(name: 'Tayikistán', code: 'TJ', flag: '🇹🇯', dialCode: '+992'),
  Country(name: 'Togo', code: 'TG', flag: '🇹🇬', dialCode: '+228'),
  Country(name: 'Tonga', code: 'TO', flag: '🇹🇴', dialCode: '+676'),
  Country(name: 'Trinidad y Tobago', code: 'TT', flag: '🇹🇹', dialCode: '+1'),
  Country(name: 'Túnez', code: 'TN', flag: '🇹🇳', dialCode: '+216'),
  Country(name: 'Turquía', code: 'TR', flag: '🇹🇷', dialCode: '+90'),
  Country(name: 'Tuvalu', code: 'TV', flag: '🇹🇻', dialCode: '+688'),
  Country(name: 'Ucrania', code: 'UA', flag: '🇺🇦', dialCode: '+380'),
  Country(name: 'Uganda', code: 'UG', flag: '🇺🇬', dialCode: '+256'),
  Country(name: 'Uruguay', code: 'UY', flag: '🇺🇾', dialCode: '+598'),
  Country(name: 'Uzbekistán', code: 'UZ', flag: '🇺🇿', dialCode: '+998'),
  Country(name: 'Vanuatu', code: 'VU', flag: '🇻🇺', dialCode: '+678'),
  Country(name: 'Venezuela', code: 'VE', flag: '🇻🇪', dialCode: '+58'),
  Country(name: 'Vietnam', code: 'VN', flag: '🇻🇳', dialCode: '+84'),
  Country(name: 'Yemen', code: 'YE', flag: '🇾🇪', dialCode: '+967'),
  Country(name: 'Yibuti', code: 'DJ', flag: '🇩🇯', dialCode: '+253'),
  Country(name: 'Zambia', code: 'ZM', flag: '🇿🇲', dialCode: '+260'),
  Country(name: 'Zimbabue', code: 'ZW', flag: '🇿🇼', dialCode: '+263'),
];
